using System;
using System.Collections.Generic;

namespace CCSSDomain.Game;



// Make this class immutable and have all the properties be generated by the GameEditingData on construction?
public class Game {

	public VersionNumber Version;

	public DateTime VersionReleaseDate;

	public string Name = "";
	public string Description = "";
	public int Year = 0;

	public List<Alliance> Alliances = new();
}