name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: CyberCavsScoutingSystem

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.200-preview.22628.1'
    - name: Install workload
      run: dotnet workload install maui-android
    - name: Install workload
      run: dotnet workload install maui-ios
    - name: Install workload
      run: dotnet workload install maui-maccatalyst
    - name: Install workload
      run: dotnet workload install maui-tizen
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build CyberCavsScoutingSystem.sln --no-restore
    - name: Test GameMakerWpf
      run: dotnet test GameMakerWpf.Tests/GameMakerWpf.Tests.csproj --no-build --verbosity normal
    - name: Test UtilitiesLibrary
      run: dotnet test UtilitiesLibrary.Tests/UtilitiesLibrary.Tests.csproj --no-build --verbosity normal
