name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: CyberCavsScoutingSystem

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build CyberCavsScoutingSystem.sln
    - name: Test CCSSDomain
      run: dotnet test CCSSDomain.Tests/CCSSDomain.Tests.csproj --no-build --verbosity normal
